export const ROLES = {
  CEO: 'CEO',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
  MARKETING: 'MARKETING',
  RND: 'RND',
  EMPLOYEE: 'EMPLOYEE',
  VIEWER: 'VIEWER',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const OTP_TYPES = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

export const TOKEN_TYPES = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

export const NOTIFICATION_TYPES = {
  EMAIL_RECEIVED: 'EMAIL_RECEIVED',
  MEETING_REMINDER: 'MEETING_REMINDER',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  AI_INSIGHT: 'AI_INSIGHT',
  COMPETITOR_ALERT: 'COMPETITOR_ALERT',
  LEAD_UPDATE: 'LEAD_UPDATE',
} as const;
